server:
  port: 8567
  servlet:
    context-path: /api

spring:
  session:
    store-type: redis
    timeout: 2592000        # 30天
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_passage_creator
    username: root
    password: '@Liu19991212'
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: ai-passage-creator

mybatis-flex:
  configuration:
    map-underscore-to-camel-case: false  # 注意：本项目关闭了驼峰映射

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true