server:
  port: 8567
  servlet:
    context-path: /api
spring:
  profiles:
    active: local


mybatis-flex:
  configuration:
    map-underscore-to-camel-case: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.liucc.passage.controller
# Knife4j/Swagger 配置
knife4j:
  enable: true
  setting:
    language: zh-CN

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true